# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Video Feature"
  description: Embedded video, title, and optional description.
  icon: play_circle
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Featured Video
  title: Video Title
  description: Video description.
  video_id: EMhV-NvxrAo
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: textarea
  is_dynamic:
    hidden: true
  video_id:
    context:
      content: This is the last part of the URL of the video you want to feature i.e. if the video URL is https://www.youtube.com/watch?v=EMhV-NvxrAo then the ID is <strong>EMhV-NvxrAo</strong>.