# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Calendar Events"
  description: Display a feed of upcoming events with dates and details.
  icon: event
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Events
  # subheading:
  event_feed:
  link_text:
  url:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  event_feed:
    type: code
    options:
      syntax: html
  heading:
    options:
      required: true
  is_dynamic:
    hidden: true
  link_text:
    label: Link to Calendar