# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_blocks
  label: "Lead Text"
  description: Large text to call out important content.
  icon: font_download
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: Text.
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true
  text:
    type: textarea