# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "YouTube Shorts"
  description: YouTube Shorts with optional title and subhead.
  icon: youtube_activity
  tags: [Photos and Videos]

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Shorts
  subheading:
  aria_label:
  shorts:
    - title:
      video_id:
      ratio: 9x16
  postscript:
    copy:
    # ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      # remove_container_background: false
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name: youtube-shorts
      edit_mode_only: false
      include_heading_postscript: true
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  aria_label:
    label: ARIA Label
    hidden: 'heading'
    options:
      required: true
    context:
      content: If your component doesn’t have a heading, it needs an <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label">ARIA label</a> to be accessible. Enter a concise label to provide a clear and useful name for this component e.g. “Featured News Stories.”
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  bg_subtle:
    type: checkbox
  buffer:
    type: select
    options:
      allow_empty: true
      values: _select_data.buffers
      value_key: class
    cascade: true
  color_palette:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
    cascade: true
  ctas:
    type: array
    options:
      structures: _structures.links
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  margin:
    type: select
    options:
      allow_empty: true
      values: _select_data.container_margins
      value_key: class
    cascade: true
  padding:
    type: auto
    hidden: true
  remove_container_background:
    hidden: true
  settings:
    type: object
    options:
      subtype: tabbed
  shorts:
    options:
      max_items: 3
  # tint_opacity:
  #   type: select
  #   options:
  #     allow_empty: true
  #     values: _select_data.tint_opacities
  #     value_key: value
  #   comment: >-
  #     Use to improve text legibility when using a background image. Disabled
  #     when blend is enabled.
  #   cascade: true
  tone:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Default
          class: default
        - name: Reserved
          class: reserved
        - name: Loud
          class: loud
        - name: Let’s Go!
          class: lets-go
      value_key: class
  copy:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  ratio:
    hidden: true
  use_common_wrapper:
    type: auto
    hidden: true
_select_data:
  buffers:
    - name: Buffer Top
      class: pt-6
    - name: Buffer Bottom
      class: pb-6
    - name: Buffer Both
      class: py-6
  color_palettes:
    - name: Option 1
      class: option-1
    - name: Option 2
      class: option-2
    - name: Option 3
      class: option-3
    - name: Option 4
      class: option-4
    - name: Option 5
      class: option-5
    - name: Option 6
      class: option-6
    - name: Option 7
      class: option-7
    - name: Option 8
      class: option-8
  container_margins:
    - name: Pull Up
      class: mt-n8 mt-xxl-n9
    - name: Pull Down
      class: mb-n8 mb-xxl-n9
    - name: Pull Both
      class: my-n8 my-xxl-n9
  # tint_opacities:
  #   - name: None
  #     value: '0.0'
  #   - name: Light
  #     value: '0.3'
  #   - name: Medium
  #     value: '0.5'
  #   - name: Dark
  #     value: '0.7'
_structures:
  links:
    values:
      - value:
          text:
          icon:
          url: