# Metadata about this component, to be used in the CMS
spec:
  structures:
    - photo_essay_blocks
    - place_blocks
  label: "Rich Text"
  description: Add formatted text.
  icon: edit_note
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text:
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true
  settings:
    config:
      name: rich-text

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  settings:
    type: object
    hidden: true
    options:
      subtype: tabbed
      code: true
  text:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  use_common_wrapper:
    type: auto
    hidden: true
