# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "People Grid"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading:
  people:
    - person:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      # enable_blend: false
      # tint_opacity: '0.7'
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name: people-grid
      edit_mode_only: false
      include_heading_postscript: true
      show_content: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  color_palette:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  margin:
    type: select
    options:
      allow_empty: true
      values: _select_data.container_margins
      value_key: class
  person:
    type: select
    options:
      allow_empty: true
      values: data.people_data
  settings:
    type: object
    options:
      subtype: tabbed
  use_common_wrapper:
    type: auto
    hidden: true