# Metadata about this component, to be used in the CMS
spec:
  structures:
    - faculty_files
  label: "Files"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name:
  file:
  icon:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  file:
    type: file
    options:
      allowed_sources:
        - ccdam