# Metadata about this component, to be used in the CMS
spec:
  structures:
    # - article_blocks
    # - column_sm_blocks
    # - detail_blocks
    # - place_blocks
  label: "HTML Markup"
  description: Add HTML inline.
  icon: code
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  markup:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true
  markup:
    type: code
    options:
      syntax: html