# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "CTA Banner"
  description: A banner with a call to action button.
  icon: campaign
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading goes here.
  buttons:
    - text:
      url:
      icon:
      # button_c:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true