# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Cards - Vertical"
  description: Cards stacked vertically (w/photos).
  icon: library_books
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  # heading: Heading
  # subheading: Subheading.
  items:
    - title: Item 1 Title
      image:
      alt_text:
      # label:
      # badge:
      markdown: Item 1 text.
      ctas:
  # postscript:
  #   copy:
  #   ctas:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  accent_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    label: Accent Color
  alt_text:
    hidden: '!image'
    options:
      required: true
  copy:
    options:
      allowed_sources:
        - ccdam
  ctas:
    type: array
    options:
      structures: _structures.links
  image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
  is_dynamic:
    hidden: true
  markdown:
    options:
      allowed_sources:
        - ccdam
_structures:
  links:
    style: select
    values:
      - value:
          text:
          icon:
          url: