# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_sidebar_blocks
  label: "Jump Links"
  description: Links that jump to sections of your page.
  icon: arrow_cool_down
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  items:
    - text: 
      anchor:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true