# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Topper - Hero w/Icons"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  background_image:
  alt_text:
  heading:
    - text: Heading
      highlight:
  subheading: Subheading.
  body_text:
  items:
    - icon: book
      text: Text
      url:
  styles:
    vibe: down-to-business
    background_c:
    gradient_1:
    gradient_2:
    gradient_3:
    heading_c:
    enable_blend: false
    enable_pattern: false
    tint_opacity: "0.5"
    container_margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  alt_text:
    hidden: '!background_image'
    options:
      required: true
  body_text:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  # container_margin:
  #   type: select
  #   options:
  #     values: _select_data.topper_margins
  #     value_key: class