# Metadata about this component, to be used in the CMS
spec:
  structures:
    - social_links_blocks
  label: "Social Links"
  description: A list of links.
  icon: add_link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  links:
    - text:
      url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
_select_data: