# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
  label: "Factoids"
  description: A banner with key stats or numeric highlights.
  icon: analytics
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: By the Numbers
  items:
    - pre: Pre text
      stat: "95%"
      post: Post text.
      source: Source
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true