# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Info Card"
  description: For including larger bodies of content.
  icon: info
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  heading_level: H3
  subheading:
  markdown:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading_level:
    type: select
    options:
      allow_empty: false
      values:
        - H2
        - H3
  is_dynamic:
    hidden: true
  markdown:
    options:
      type: markdown
      blockquote: true
      bold: true
      bulletedlist: true
      embed: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      image: false
      indent: true
      join_above: true
      join_below: true
      link: true
      numberedlist: true
      outdent: true
      strike: true
      subscript: true
      superscript: true
      table: true
      underline: true
      code: true
      style: /assets/scss/custom/_content.scss
      allowed_sources:
        - ccdam