# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Teasers - Generic"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  items:
    - heading: Heading
      icon: book
      tags: []
      ctas:
        - text: View All
          icon: arrow-circle-right
          url:
  show_content: false
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true