# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
  label: "Benefits Checklist"
  description: List of product benefits.
  icon: checklist
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  items:
    - title: Item 1 Title
      text: Item 1 text.
  ctas:
  benefits_icon: circle-check
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  badge:
    hidden: true
  config:
    hidden: true
  ctas:
    type: array
    options:
      structures: _structures.links
  is_dynamic:
    hidden: true
  layout:
    hidden: true
  label:
    hidden: true
  text:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  title:
    options:
      required: false
  benefits_icon:
    label: Icon
    type: select
    options:
      values:
        - name: Checkmark
          class: circle-check
        - name: Arrow
          class: arrow-circle-right
        - name: Plus
          class: circle-plus
      value_key: class
_structures:
  links:
    style: select
    values:
      - value:
          text:
          icon:
          url: