# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
    - detail_sidebar_blocks
  label: "Faculty Members"
  description: Profiles of faculty with names, titles, and photos.
  icon: person_add
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Faculty
  tags:
  # postscript:
  #   copy:
  #   ctas:
  is_dynamic: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  copy:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  is_dynamic:
    hidden: true
  tags:
    type: multiselect
    options:
      allow_create: true
      allow_empty: true
      values:
        - featured