# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Cards - Simple - Vertical"
  description: Cards stacked vertically (no photos).
  icon: library_books
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  items:
    - title: Item 1 Title
      text: Item 1 text.
      url:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true